spring:
  application:
    name: feign-demo
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
logging:
  level:
    root: info
