spring:
  application:
    name: feign-inherit-provide
server:
  port: 8087
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}