spring:
  application:
    name: ribbon-demo
server:
  port: 8084
eureka:
  client:
    service-url:
      # 注册到eureka-server
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    # 采用ip注册
    prefer-ip-address: true
    # 定义实例id格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
ribbon:
  eager-load:
    enabled: true
    clients: ribbon-demo