spring:
  application:
    name: hystrix-demo
server:
  port: 8089
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
logging:
  level:
    root: info