spring:
  application:
    name: zuul-file-demo
server:
  port: 8093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
zuul:
  routes:
    zuul-file-demo:
      path: /zuul-file-demo/**
      url: forward:/
management:
  endpoints:
    web:
      exposure:
        include: "*"
